# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\code\entreada.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(516, 294)
        MainWindow.setStyleSheet("background-color: rgb(167, 126, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 0, 291, 91))
        self.label.setStyleSheet("background-color: rgb(167, 126, 255);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 140, 121, 41))
        self.pushButton_2.setStyleSheet("background-color: rgb(167, 126, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"OCR A Extended\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(80, 140, 121, 41))
        self.pushButton.setStyleSheet("background-color: rgb(167, 126, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"OCR A Extended\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.raise_()
        self.label.raise_()
        self.pushButton_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 516, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">Bienvenido </span></p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "Salir"))
        self.pushButton.setText(_translate("MainWindow", "Entrar"))
import ded_rc
import eded_rc
