# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\code\resela.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(882, 572)
        MainWindow.setStyleSheet("\n"
"background-color:rgb(170, 85, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 241, 41))
        self.label.setStyleSheet("background-color: rgb(170, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(270, 20, 461, 20))
        self.lineEdit.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(170, 170, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 261, 31))
        self.label_2.setStyleSheet("background-color: rgb(170, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 190, 251, 31))
        self.label_3.setStyleSheet("\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"color:white")
        self.label_3.setObjectName("label_3")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(280, 180, 441, 181))
        self.plainTextEdit.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(170, 170, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(30, 400, 211, 51))
        self.checkBox.setStyleSheet("background-color:rgb(170, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 16pt \"OCR A Extended\";")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(240, 400, 251, 51))
        self.checkBox_2.setStyleSheet("background-color:rgb(170, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 16pt \"OCR A Extended\";")
        self.checkBox_2.setObjectName("checkBox_2")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(290, 100, 42, 22))
        self.spinBox.setStyleSheet("background-color:rgb(170, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"OCR A Extended\";")
        self.spinBox.setMaximum(10)
        self.spinBox.setObjectName("spinBox")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(360, 80, 521, 41))
        self.label_4.setStyleSheet("\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"color:white")
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(550, 380, 171, 31))
        self.pushButton.setStyleSheet("background-color:rgb(170, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"OCR A Extended\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(550, 420, 171, 31))
        self.pushButton_2.setStyleSheet("background-color:rgb(170, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"OCR A Extended\";")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 882, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Titulo de la pelicula:</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Raiting de la pelicula :</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Reseña de la pelicula::</span></p></body></html>"))
        self.checkBox.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Recomendada :</span></p></body></html>"))
        self.checkBox.setText(_translate("MainWindow", "Recomendada "))
        self.checkBox_2.setText(_translate("MainWindow", "No recomendada"))
        self.label_4.setText(_translate("MainWindow", "0=pesima 5=neutral  10=excelente"))
        self.pushButton.setText(_translate("MainWindow", "Guardar"))
        self.pushButton_2.setText(_translate("MainWindow", "Descartar"))
